Add support for negative values for reg limits
webkom/lego pull request #2047
Opened 2021-02-07 17:21 UTC by odinuge

2021-02-07 17:52 UTC, SmithPeder requested changes

2021-02-07 17:52 UTC, SmithPeder commented on lego/apps/events/websockets.py
> +    Since we use websockets for registrations and event description uptdates, include events
```suggestion
    Since we use websockets for registrations and event description updates, include events
```

2021-02-07 17:52 UTC, SmithPeder commented on lego/apps/events/websockets.py
> +    Since we use websockets for registrations and event description uptdates, include events
😄

2021-02-07 17:54 UTC, SmithPeder approved these changes

2021-02-08 16:19 UTC, LudvigHz approved these changes

2021-02-08 16:20 UTC, merged