[WIP] Add ProgressiveImageField
webkom/lego pull request #2479
Opened 2022-01-16 18:56 UTC by LudvigHz

This field can be used to automatically create a placeholder image beside the full image, that can be used as a placeholder.

2022-02-09 16:34 UTC, LudvigHz commented
### UPDATE:
Now with less content shift and more/better loading. I have gone through and most places now should not shift content at all when partially loading.

Also: there were some really wonky stuff with the articles page that I hadn't noticed before, like misaligned items and weird borders. Should be good now :smile: 

https://user-images.githubusercontent.com/42850232/153245458-51543555-5fa4-4401-ad07-b7b5fa578336.mp4

https://user-images.githubusercontent.com/42850232/153245591-9514ea45-e486-456f-ab67-6354ca161527.mp4

2022-02-09 17:24 UTC, SmithPeder requested changes
If i get the schema correctly, my comments make sense?

2022-02-09 17:24 UTC, SmithPeder commented on lego/apps/articles/serializers.py
> +        source="cover", required=False, options={"height": 50, "filters": ["blur(20)"]}
this should be 30 ey?

2022-02-09 19:05 UTC, LudvigHz commented on lego/apps/companies/serializers.py
> +        source="logo", required=False, options={"height": 500, "filters": ["blur(20)"]}
oh damn. yup

2022-02-09 19:05 UTC, LudvigHz commented on lego/apps/articles/serializers.py
> +        source="cover", required=False, options={"height": 50, "filters": ["blur(20)"]}
yup

2022-02-15 08:26 UTC, LudvigHz commented
> Shouldn't the SearchArticleSerializer class also use a cover placeholder?

No. This is intentional, as this serializer is only used when searching, where we don't use the cover. If you think it should, sure. But I don't think it needs to be there. (We don't use the cover on lego-webapp at least).

2022-02-15 14:51 UTC, SmithPeder approved these changes

2022-02-20 15:39 UTC, merged