Improve weekly mail
webkom/lego pull request #3200
Opened 2023-02-02 14:03 UTC by erlingfn

Improve the css of the joblistings table. Hard code date and times being displayed in Norwegian time.

2023-02-02 14:14 UTC, ivarnakken requested changes
💯 Word break was much needed

2023-02-02 14:14 UTC, ivarnakken commented on lego/apps/email/tasks.py
> +import pytz
Support for `pytz` was deprecated from [Django v4](https://docs.djangoproject.com/en/4.1/releases/4.0/#zoneinfo-default-timezone-implementation). Use `zoneinfo` instead.

2023-02-02 14:58 UTC, LudvigHz approved these changes
LGTM (except for the `tzinfo` ofc)

2023-02-03 12:44 UTC, norbye approved these changes

2023-02-07 18:14 UTC, ivarnakken approved these changes

2023-02-07 21:11 UTC, merged