Change author on articles from one to many
webkom/lego pull request #3220
Opened 2023-02-13 15:44 UTC by jonasdeluna

![image](https://user-images.githubusercontent.com/113468143/218504164-5c837712-715b-4635-b9d8-ede57e60b3f4.png)

2023-02-21 22:03 UTC, LudvigHz requested changes

2023-02-21 22:03 UTC, LudvigHz commented on lego/apps/articles/models.py
> +    author = ManyToManyField(User)
This should be `authors`, no? (i.e. plural)

2023-02-21 22:03 UTC, LudvigHz commented on lego/apps/articles/serializers.py
> +    #    author = serializers.ListField(child=PublicUserSerializer(read_only=True))
same here

2023-03-13 17:35 UTC, LudvigHz requested changes
Nice :ok_hand:. Just a few small things she this is good to go

2023-03-13 17:35 UTC, LudvigHz commented on lego/apps/articles/migrations/0012_rename_author_article_authors.py
> +
You should delete the two migrations you have here and create a new one. The reason is that we don't want unnecessary migrations in prod. You can just delete both of there, reset your db locally and run makemimgrations again to fix it :)

2023-03-13 17:35 UTC, LudvigHz commented on lego/apps/articles/serializers.py
> +    )
Do we want to allow null?

2023-03-14 21:08 UTC, ivarnakken approved these changes
Awesome! I'm excited to get this in 🚀 

Just fix up Ludvig's tiny comment and we're good!

2023-03-19 11:44 UTC, jonasdeluna commented
Tests are failing is that supposed to happen

2023-03-19 12:32 UTC, PeterJFB commented
> Tests are failing is that supposed to happen

Yess
![image](https://user-images.githubusercontent.com/42469466/226175206-e7bb8421-16cb-4c06-a98e-f94855fd1d5d.png)


Failing likely since the tests now need to use the `authors`-field instead of `author`. All of them use the `get_data_with_author` function in `test_articles_api.py`, changing it to an array should fix it :)

2023-03-20 10:21 UTC, merged