Add leaderboard and overview of achievements
webkom/lego pull request #3686
Opened 2024-11-10 12:55 UTC by jonasdeluna

2024-11-13 21:00 UTC, eikhr approved these changes

2024-11-13 21:01 UTC, eikhr reviewed
I think this might become slow with all users in prod, but I'm not sure how to improve it...

2025-01-15 17:14 UTC, danielyanghansen requested changes
Overall looks good.
Pagination of the `LeaderBoardViewSet.get_queryset` would be nice, but can be done in a later PR.

2025-01-15 17:14 UTC, danielyanghansen commented on lego/apps/achievements/utils/calculation_utils.py
> +    max(rarity_list) + 1 + (max(rarity_list) * delta)
Why does this work? `rarity_list` doesn't seem to be defined at this point

2025-01-15 17:14 UTC, danielyanghansen commented on lego/apps/achievements/utils/calculation_utils.py
> +    max(rarity_list) + 1 + (max(rarity_list) * delta)
I think this is going to give you a runtime error. If this code works, it seems to be because of unintended behavior

2025-01-15 17:14 UTC, danielyanghansen commented on lego/apps/achievements/utils/calculation_utils.py
> +    return score if MAX_POSSIBLE_SCORE else 0
I'm not quite sure why the presence of `MAX_POSSIBLE_SCORE` would matter here

2025-01-15 17:14 UTC, danielyanghansen commented on lego/apps/users/models.py
> +        from lego.apps.achievements.utils.calculation_utils import calculate_user_rank
Could you educate me on the benefits of a late import like this? :angel:

2025-01-29 12:36 UTC, jonasdeluna commented on lego/apps/achievements/utils/calculation_utils.py
> +    max(rarity_list) + 1 + (max(rarity_list) * delta)
This is apparently due to a quirk in python as the defenition depends on a dictionary that already exists it apparently works

2025-01-29 19:35 UTC, merged